// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package config

import (
	json "encoding/json"
	easyjson "github.com/davidlazar/easyjson"
	jlexer "github.com/davidlazar/easyjson/jlexer"
	jwriter "github.com/davidlazar/easyjson/jwriter"
	mixnet "vuvuzela.io/alpenhorn/mixnet"
	pkg "vuvuzela.io/alpenhorn/pkg"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDecodeConfigMsg6615c02e(in *jlexer.Lexer, out *configMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Created":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Created).UnmarshalJSON(data))
			}
		case "Expires":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Expires).UnmarshalJSON(data))
			}
		case "PrevConfigHash":
			out.PrevConfigHash = string(in.String())
		case "Service":
			out.Service = string(in.String())
		case "Inner":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Inner).UnmarshalJSON(data))
			}
		case "Guardians":
			if in.IsNull() {
				in.Skip()
				out.Guardians = nil
			} else {
				in.Delim('[')
				if out.Guardians == nil {
					if !in.IsDelim(']') {
						out.Guardians = make([]Guardian, 0, 1)
					} else {
						out.Guardians = []Guardian{}
					}
				} else {
					out.Guardians = (out.Guardians)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Guardian
					(v1).UnmarshalEasyJSON(in)
					out.Guardians = append(out.Guardians, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Signatures":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Signatures = make(map[string][]uint8)
				} else {
					out.Signatures = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 []uint8
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						v2 = in.BytesReadable()
					}
					(out.Signatures)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEncodeConfigMsg6615c02e(out *jwriter.Writer, in configMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Created\":")
	out.Raw((in.Created).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Expires\":")
	out.Raw((in.Expires).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"PrevConfigHash\":")
	out.String(string(in.PrevConfigHash))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Service\":")
	out.String(string(in.Service))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Inner\":")
	out.Raw((in.Inner).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Guardians\":")
	if in.Guardians == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v4, v5 := range in.Guardians {
			if v4 > 0 {
				out.RawByte(',')
			}
			(v5).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Signatures\":")
	if in.Signatures == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v6First := true
		for v6Name, v6Value := range in.Signatures {
			if !v6First {
				out.RawByte(',')
			}
			v6First = false
			out.String(string(v6Name))
			out.RawByte(':')
			out.Base32Bytes(v6Value)
		}
		out.RawByte('}')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v configMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeConfigMsg6615c02e(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v configMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeConfigMsg6615c02e(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *configMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeConfigMsg6615c02e(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *configMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeConfigMsg6615c02e(l, v)
}
func easyjsonEncodeSignedConfig6615c02e(out *jwriter.Writer, in SignedConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Service\":")
	out.String(string(in.Service))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Created\":")
	out.Raw((in.Created).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Expires\":")
	out.Raw((in.Expires).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"PrevConfigHash\":")
	out.String(string(in.PrevConfigHash))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Inner\":")
	if m, ok := in.Inner.(easyjson.Marshaler); ok {
		m.MarshalEasyJSON(out)
	} else if m, ok := in.Inner.(json.Marshaler); ok {
		out.Raw(m.MarshalJSON())
	} else {
		out.Raw(json.Marshal(in.Inner))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Guardians\":")
	if in.Guardians == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v9, v10 := range in.Guardians {
			if v9 > 0 {
				out.RawByte(',')
			}
			(v10).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Signatures\":")
	if in.Signatures == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v11First := true
		for v11Name, v11Value := range in.Signatures {
			if !v11First {
				out.RawByte(',')
			}
			v11First = false
			out.String(string(v11Name))
			out.RawByte(':')
			out.Base32Bytes(v11Value)
		}
		out.RawByte('}')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignedConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeSignedConfig6615c02e(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignedConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeSignedConfig6615c02e(w, v)
}
func easyjsonDecodeGuardian6615c02e(in *jlexer.Lexer, out *Guardian) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Username":
			out.Username = string(in.String())
		case "Key":
			if in.IsNull() {
				in.Skip()
				out.Key = nil
			} else {
				out.Key = in.BytesReadable()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEncodeGuardian6615c02e(out *jwriter.Writer, in Guardian) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Username\":")
	out.String(string(in.Username))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Key\":")
	out.Base32Bytes(in.Key)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Guardian) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeGuardian6615c02e(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Guardian) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeGuardian6615c02e(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Guardian) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeGuardian6615c02e(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Guardian) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeGuardian6615c02e(l, v)
}
func easyjsonDecodeDialingConfig6615c02e(in *jlexer.Lexer, out *DialingConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Coordinator":
			(out.Coordinator).UnmarshalEasyJSON(in)
		case "MixServers":
			if in.IsNull() {
				in.Skip()
				out.MixServers = nil
			} else {
				in.Delim('[')
				if out.MixServers == nil {
					if !in.IsDelim(']') {
						out.MixServers = make([]mixnet.PublicServerConfig, 0, 1)
					} else {
						out.MixServers = []mixnet.PublicServerConfig{}
					}
				} else {
					out.MixServers = (out.MixServers)[:0]
				}
				for !in.IsDelim(']') {
					var v17 mixnet.PublicServerConfig
					(v17).UnmarshalEasyJSON(in)
					out.MixServers = append(out.MixServers, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "CDNServer":
			(out.CDNServer).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEncodeDialingConfig6615c02e(out *jwriter.Writer, in DialingConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Coordinator\":")
	(in.Coordinator).MarshalEasyJSON(out)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"MixServers\":")
	if in.MixServers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v18, v19 := range in.MixServers {
			if v18 > 0 {
				out.RawByte(',')
			}
			(v19).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"CDNServer\":")
	(in.CDNServer).MarshalEasyJSON(out)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DialingConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeDialingConfig6615c02e(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DialingConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeDialingConfig6615c02e(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DialingConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeDialingConfig6615c02e(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DialingConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeDialingConfig6615c02e(l, v)
}
func easyjsonDecodeCoordinatorConfig6615c02e(in *jlexer.Lexer, out *CoordinatorConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Key":
			if in.IsNull() {
				in.Skip()
				out.Key = nil
			} else {
				out.Key = in.BytesReadable()
			}
		case "Address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEncodeCoordinatorConfig6615c02e(out *jwriter.Writer, in CoordinatorConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Key\":")
	out.Base32Bytes(in.Key)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Address\":")
	out.String(string(in.Address))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CoordinatorConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeCoordinatorConfig6615c02e(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CoordinatorConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeCoordinatorConfig6615c02e(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CoordinatorConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeCoordinatorConfig6615c02e(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CoordinatorConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeCoordinatorConfig6615c02e(l, v)
}
func easyjsonDecodeCDNServerConfig6615c02e(in *jlexer.Lexer, out *CDNServerConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Key":
			if in.IsNull() {
				in.Skip()
				out.Key = nil
			} else {
				out.Key = in.BytesReadable()
			}
		case "Address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEncodeCDNServerConfig6615c02e(out *jwriter.Writer, in CDNServerConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Key\":")
	out.Base32Bytes(in.Key)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Address\":")
	out.String(string(in.Address))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CDNServerConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeCDNServerConfig6615c02e(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CDNServerConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeCDNServerConfig6615c02e(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CDNServerConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeCDNServerConfig6615c02e(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CDNServerConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeCDNServerConfig6615c02e(l, v)
}
func easyjsonDecodeAddFriendConfig6615c02e(in *jlexer.Lexer, out *AddFriendConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Coordinator":
			(out.Coordinator).UnmarshalEasyJSON(in)
		case "PKGServers":
			if in.IsNull() {
				in.Skip()
				out.PKGServers = nil
			} else {
				in.Delim('[')
				if out.PKGServers == nil {
					if !in.IsDelim(']') {
						out.PKGServers = make([]pkg.PublicServerConfig, 0, 1)
					} else {
						out.PKGServers = []pkg.PublicServerConfig{}
					}
				} else {
					out.PKGServers = (out.PKGServers)[:0]
				}
				for !in.IsDelim(']') {
					var v26 pkg.PublicServerConfig
					(v26).UnmarshalEasyJSON(in)
					out.PKGServers = append(out.PKGServers, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "MixServers":
			if in.IsNull() {
				in.Skip()
				out.MixServers = nil
			} else {
				in.Delim('[')
				if out.MixServers == nil {
					if !in.IsDelim(']') {
						out.MixServers = make([]mixnet.PublicServerConfig, 0, 1)
					} else {
						out.MixServers = []mixnet.PublicServerConfig{}
					}
				} else {
					out.MixServers = (out.MixServers)[:0]
				}
				for !in.IsDelim(']') {
					var v27 mixnet.PublicServerConfig
					(v27).UnmarshalEasyJSON(in)
					out.MixServers = append(out.MixServers, v27)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "CDNServer":
			(out.CDNServer).UnmarshalEasyJSON(in)
		case "RegistrarHost":
			out.RegistrarHost = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEncodeAddFriendConfig6615c02e(out *jwriter.Writer, in AddFriendConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Coordinator\":")
	(in.Coordinator).MarshalEasyJSON(out)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"PKGServers\":")
	if in.PKGServers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v28, v29 := range in.PKGServers {
			if v28 > 0 {
				out.RawByte(',')
			}
			(v29).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"MixServers\":")
	if in.MixServers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v30, v31 := range in.MixServers {
			if v30 > 0 {
				out.RawByte(',')
			}
			(v31).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"CDNServer\":")
	(in.CDNServer).MarshalEasyJSON(out)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"RegistrarHost\":")
	out.String(string(in.RegistrarHost))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddFriendConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeAddFriendConfig6615c02e(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddFriendConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeAddFriendConfig6615c02e(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddFriendConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeAddFriendConfig6615c02e(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddFriendConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeAddFriendConfig6615c02e(l, v)
}
